apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: mysql-init
          image: mysql:8.0.43
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: task-planner-configmap
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: task-planner-configmap
                  key: MYSQL_ROOT_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-planner-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: task-planner-configmap
                  key: MYSQL_TODO_DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: task-planner-configmap
                  key: MYSQL_TODO_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-planner-secret
                  key: MYSQL_TODO_PASSWORD
          volumeMounts:
            - name: init-sql
              mountPath: /init
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for MySQL DNS to be resolvable..."
              until getent hosts mysql-0.mysql.task-planner.svc.cluster.local; do
                echo "Waiting for DNS to resolve..."
                sleep 5
              done

              echo "DNS resolved. Waiting for MySQL to accept connections..."
              until mysqladmin ping -h "$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" --silent; do
                echo "Waiting for MySQL to be ready..."
                sleep 5
              done
              echo "MySQL is ready! Running init scripts..."
              envsubst < /init/init-db-template.sql | mysql -h "$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"
              echo "init scripts run step is completed..."
      restartPolicy: OnFailure
      volumes:
        - name: init-sql
          configMap:
            name: mysql-init-script-configmap
