apiVersion: v1
kind: ConfigMap
metadata:
  name: task-planner-configmap
  namespace: task-planner
data:
  MYSQL_HOST: "localhost"
  MYSQL_PORT: "3306"
  MYSQL_ROOT_USER: "root"
  MYSQL_TODO_DB_NAME: "todo_db"
  MYSQL_TODO_USER: "todo_user"